### ISSUE TITLE
Add flag for only installing dependencies

### ISSUE THREAD

**Issue by magneticflux-** [limjh16/jekyll-action-ts#11]
I want to install dependencies for linting using the cache, but don't want to spend the time building the site.

**Comment by limjh16** [comment]
Hi there! may I know what is the use case for this feature?

**Comment by magneticflux-** [comment]
I want to simply install Bundler dependencies using the cache without running a page build.

**Comment by limjh16** [comment]
In that case, I don't think this action would be suitable since it is mainly used for jekyll pages, so if you don't run the page build then I don't really see the need for this. Maybe you can try using https://github.com/ruby/setup-ruby/, it may suit your needs better.

**Comment by magneticflux-** [comment]
Sorry, I didn't realize `setup-ruby` already handled caching bundler dependencies here: https://github.com/ruby/setup-ruby/#caching-bundle-install-automatically
I think using that makes a lot more sense in an advanced use-case like this!
