### ISSUE TITLE
Feature request: support for build options

### ISSUE THREAD

**Issue by nickswalker** [limjh16/jekyll-action-ts#2]
Jekyll has several build options which be handy when you want to deploy to a staging website: https://jekyllrb.com/docs/configuration/options/

These could be exposed by adding a new string option that would be handed as extra arguments to the build step.

**Comment by limjh16** [comment]
Hi, sorry for the late reply. This seems like a good idea, will do this sometime soon!

**Comment by limjh16** [comment]
Hi, I just added an input for Jekyll build options, you can try it by adding
```diff
  uses: limjh16/jekyll-action-ts@v2
  with:
+   custom_opts: '--drafts --lsi --blabla'
```
