### ISSUE TITLE
Bump node version

### ISSUE THREAD

**Issue by cryptoAlgorithm** [limjh16/jekyll-action-ts#32]
Currently, this action runs on node 12, which will be deprecated soon and causes a warning every action run. Simply moving to node 16 should solve this problem, and allow fixing any bugs that might arise from the switch earlier, before all node 12 actions are forced to run on node 16.

**Comment by limjh16** [comment]
https://github.com/limjh16/jekyll-action-ts/pull/33#issuecomment-1477242381
