### ISSUE TITLE
Error: The process '/opt/hostedtoolcache/Ruby/2.6.10/x64/bin/bundle' failed with exit code 1

### ISSUE THREAD

**Issue by antoyo** [limjh16/jekyll-action-ts#34]
Hi.
I just ran into this issue in [my CI](https://github.com/antoyo/jekyll-antoyo-blog/actions/runs/3588348445/jobs/6039905822#step:4:77).
Thanks to fix this issue.

**Comment by Thysbelon** [comment]
I had a [similar issue](https://github.com/Thysbelon/Thysbelon.github.io/actions/runs/3635974653/jobs/6135544964#step:4:60),
[changing the Ruby version to 2.7 fixed it](https://github.com/Thysbelon/Thysbelon.github.io/commit/c1ba672e4562c4270e8056a3efdd3ba69009b0f5).
Hope this helps.

**Comment by limjh16** [comment]
https://github.com/limjh16/jekyll-action-ts/commit/c5e4c83672987df379d6924ca6dfa8891ac1c067
