### ISSUE TITLE
Transition to Node 20

### ISSUE THREAD

**Issue by mykolamor** [limjh16/jekyll-action-ts#38]
I keep getting the warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: limjh16/jekyll-action-ts@v2

As per [this reference](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) the action should be updated. Would that be possible?

**Comment by mykolamor** [comment]
Thanks! Would it be possible to make a new release after the CI/CD is complete? It would be a bit annoying to reference the specific commit instead of a simple `@v3`.

**Comment by limjh16** [comment]
Yep, did that already, was just waiting for the runner to finish so I can confirm this doesn't break anything. Should still work with 
`@v2`
