### ISSUE TITLE
Failure to use config

### ISSUE THREAD

**Issue by MinusGix** [limjh16/jekyll-action-ts#8]
While building (https://github.com/MinusGix/minusgix.github.io/tree/master ), the output appears to fail to use my configuration as it does not use the theme nor does it appear to use katex.  
It works on my local machine (Manjaro Linux), with these versions:  
Bundle: 2.1.4  
Gem: 3.1.4  
Ruby: 2.7.1p83  
Log from github actions: https://gist.github.com/MinusGix/7563cc94d85cbcdcf5ed0c683f3bb3e4  
It appears to use ruby 2.7, bundler 2.1.4, and probably the correct jekyll version, so I'm not sure what the issue is. Do you have any ideas?

**Comment by limjh16** [comment]
Hi, from a quick look at your _config.yml it seems like there is nothing wrong, and the output on your gh-pages branch seems fine as well, with the theme built in. Could you go to check your repository settings, and see that under "GitHub Pages" the source branch is gh-pages?

**Comment by MinusGix** [comment]
Thanks! I feel foolish now.
