### ISSUE TITLE
Bundle does not install

### ISSUE THREAD

**Issue by UriShX** [limjh16/jekyll-action-ts#9]
When jekyll-action-ts runs on [my blog](https://github.com/UriShX/microblog) the build fails, returning `ENOENT: no such file or directory, open '/home/runner/work/microblog/microblog/Gemfile.lock'` followed by `Gemfile.lock probably needs updating. Run "bundle install" locally and commit changes. Exiting action`. \
I tried running locally and submitting Gemfile.lock, but had problems with local overrides for the theme's Sass files. Specifically, it does not seem to link correctly, causing some styles to be rendered directly from the theme's styles. I am pulling the theme in the Gemfile directly from Github.
I couldn't find how to retrieve a log for the action, if you can point me to a tutorial I'll share it here. In the meantime, you can see a failed deployment [here](https://github.com/UriShX/microblog/actions/runs/320696337).
Thanks!

**Comment by limjh16** [comment]
Hey, the log is [here](https://github.com/UriShX/microblog/runs/1289096716?check_suite_focus=true#step:4:17). Looking through your repository, it does not seem like you have a Gemfile.lock file. It should not be affected by your Sass files, that is a separate issue. Maybe you can try these commands:
```sh
git add Gemfile.lock
git commit -m "add Gemfile.lock"
git push
```

**Comment by UriShX** [comment]
Hi, Thanks for the quick reply.
I thought line 163: `bundle install --jobs=4 --retry=3 --gemfile=${gemSrc}` was supposed to do that. I uploaded the Gemfile.lock and it now works fine.
For some reason the Sass files also compile as they should now. Don't really know why.
Thanks again

**Comment by limjh16** [comment]
since this is a [deployment](https://github.com/limjh16/jekyll-action-ts/blob/master/src/main.ts#L157) action, the bundle install command will only install whatever is in the lockfile rather than what is in the Gemfile to ensure that the versions of software installed are fully compatible.

**Comment by UriShX** [comment]
Thanks for the explanation. I'll keep that in mind.
